export const FETCH_PRINTERS_SUCCEEDED = 'PRINTERS/FETCH_PRINTERS_SUCCEDED';
export const DELETE_PRINTERS_SUCCEEDED = 'PRINTERS/DELETE_PRINTERS_SUCCEDED';
export const CREATE_PRINTERS_SUCCEEDED = 'PRINTERS/CREATE_PRINTERS_SUCCEDED';
export const UPDATE_PRINTERS_SUCCEEDED = 'PRINTERS/UPDATE_PRINTERS_SUCCEDED';

