export const TAB_CHANGE = 'USER/TAB_CHANGE';
export const AUTHENTICATE = 'USER/AUTHENTICATE';
export const AUTHENTICATE_SUCCEEDED = 'USER/AUTHENTICATE_SUCCEEDED';
export const AUTHENTICATE_FAILED = 'USER/AUTHENTICATE_FAILED';
export const LOGOUT = 'USER/LOGOUT';
