export const CHECK_AGE_REQUIREMENT = 'REGISTER/CHECK_AGE_REQUIREMENT';
export const SET_ERROR_MESSAGES = 'LOGIN/SET_ERROR_MESSAGES';
export const UNSERT_ERROR_MESSAGES = 'LOGIN/UNSET_ERROR_MESSAGES';
