export const SET_STEP = 'DECORATION_ADD/NEXT_STEP';
export const COMPLETED = 'DECORATION_ADD/COMPLETED';
export const SET_NEW_DECORATION = 'DECORATION_ADD/SET_NEW_DECORATION';
export const SET_TILE_ID = 'DECORATION/SET_TILE_ID';
