export const FETCH_BOOK = 'DETAIL/FETCH_BOOK';
export const FETCH_BOOK_SUCCEEDED = 'DETAIL/FETCH_BOOK_SUCCEEDED';
export const FETCH_BOOK_FAILED = 'DETAIL/FETCH_BOOK_FAILED';

export const FETCH_DECORATIONS = 'DETAIL/FETCH_DECORATIONS';
